<?PHP
  
define('SQLHOST', 'localhost');
define('SQLUSER', 'root');
define('SQLPASS', 'root');
define('SQLDB', 'voyagermed');

$conn = mysql_connect(SQLHOST, SQLUSER, SQLPASS);
mysql_select_db(SQLDB);
      
$param = $_REQUEST['param'];
if($param == "1")
{      
    $sql = "SELECT id, title FROM doctors where id<296";
    $q = mysql_query($sql, $conn); 

    $count = 0;  
    while ($row = mysql_fetch_assoc($q)) {
        echo($row['id'] . " => " . $row['title'] . "<br>");
        $count++;
    }

    echo($count);
}
else if($param=="2")
{
    $data = array(
2 => 'Boris Ackerman MD',
3 => 'Stefan Adair MD',
4 => 'Anthony Admire MD',
5 => 'Fransicso Agullo MD',
7 => 'Bernard Alpert MD, FACS',
8 => 'Darrick Antell DDS, MD',
9 => 'Mark Anton MD, FACS',
11 => 'Sherrell Aston MD',
12 => 'John Anthony Ayala FACS, MD',
13 => 'Ramtin Kassir, M.D.',
14 => 'Dr. Alizadeh',
17 => 'Eleanor Barone MD',
18 => 'Alfonso Barrera FACS, MD',
19 => 'Richard A. Baxter MD',
20 => 'Joel B. Beck MD, FACS',
21 => 'Hilton Becker FRCS, FACS, MD',
25 => 'Thomas Biggs MD',
26 => 'Michael A. Bogdan MD',
27 => 'Matthew J. Bonanno MD, FACS',
29 => 'A. Mark Boustred MD, FACS',
30 => 'Gary Branfman MD',
31 => 'Daniel Brauman MD, MBBS, FACS',
32 => 'Harold W. Brown MD',
33 => 'Jamal Bullocks MD',
34 => 'Juris Bunkis MD',
35 => 'Jay Wynn Calvert MD',
37 => 'James H. Carraway FACS, MD',
38 => 'Laurie A. Casas FACS, MD',
39 => 'Shim Ching MD',
40 => 'Michael E. Ciaravino MD',
41 => 'Dennis P. Cirillo MD',
43 => 'Mark Clemens MD',
45 => 'Mark A. Codner MD',
46 => 'Steven Cohen MD',
47 => 'Sydney Coleman MD',
48 => 'Donald Collins MD',
50 => 'George Commons MD',
53 => 'John P. Connors MD',
56 => 'Christopher M. Craft MD',
59 => 'Kimball Crofts MD',
62 => 'Richard D\'amico MD',
63 => 'Hootan Daneshmand MD',
64 => 'Dimitrios Danikas MD, FACS',
67 => 'Jorge DE LA Torre FACS, MD',
68 => 'Gabriel DEL Corral MD',
70 => 'Michael Diaz MD',       
71 => 'Barry Dibernardo MD, FACS',
73 => 'Lisa Difrancesco MD',
74 => 'Marek Dobke MD',
75 => 'Diane I. Duncan MD',
76 => 'Alan Durkin MD',
78 => 'Felmont F. Eaves III MD, FACS',
79 => 'Herbert A. Ecker MD, FACS, DMD',
80 => 'Michael Edwards MD',
81 => 'Michael L. Eisemann MD',
82 => 'Mel Ortega MD',
83 => 'L. Franklyn Elliott MD',
84 => 'Lawrence Scott Ennis MD, FACS',
85 => 'Robert Ersek MD',
86 => 'David Evdokimow MD',
88 => 'James Fernau MD',
89 => 'Julius Few MD',
90 => 'Jack Fisher MD',
91 => 'Robert S. Flowers MD',
92 => 'Peter Fodor MD',
93 => 'Art Foley MD',
95 => 'Jack A. Friedland MD',
97 => 'Candido E. Fuentes-FELIX MD',
98 => 'Wendell Funk MD',
99 => 'David Furnas MD',
100 => 'Allen Gabriel MD',
101 => 'Miguel Gallegos MD, FACS',
102 => 'G. Gregory Gallico, MD',
104 => 'Onelio Garcia MD',
105 => 'Michael Gartner MD, FACS',
106 => 'Herve Gentile MD',
107 => 'Ashkan Ghavami MD',
108 => 'Alan Gold MD',
109 => 'Stephen A. Goldstein MD',
110 => 'Ashley Gordon MD',
111 => 'Robert Harold Gotkin MD, FACS',
112 => 'Lawrence Gray MD',
114 => 'James Grotting MD',
115 => 'Sanjay Grover MD',
116 => 'Ronald P. Gruber MD',
117 => 'Joseph Gryskiewicz FACS, MD',
118 => 'Stanley Gulin MD',            
120 => 'David Halpern MD',
121 => 'Robert S. Hamas MD',
122 => 'Adam Hisham Hamawy MD',
123 => 'Barbara Hayden MD',
125 => 'Haideh Hirmand MD',
126 => 'Paul C. Hobar MD',
127 => 'Leonard Hochstein MD',
131 => 'Charles Hughes MD',
132 => 'Joseph Hunstad MD, FACS',
133 => 'Nicanor Isse MD',
134 => 'Ronald Iverson MD, FACS',
136 => 'Gary Jacobs MD, FACS',
137 => 'Glenn Jelks MD, FACS',
139 => 'Mark L. Jewell MD',
141 => 'David Kahn MD',
142 => 'Michael Kane MD',
143 => 'Nolan Karp MD, FACS',
144 => 'Jeffrey Kenkel MD, FACS',
146 => 'Dana Khuthaila MD',
147 => 'Joseph Kiener MD, FACS',
148 => 'Brian M. Kinney MD',
151 => 'Bill Kortesis MD',
156 => 'Gregory Latrenta MD',
157 => 'Cap Lesesne FACS, MD',
158 => 'Richard A. Levine DDS, MD',
159 => 'Maria Helena Lima MD',
161 => 'Clyde Litton MD',
162 => 'Z. Paul Lorenc MD',
163 => 'Candis Lovelace MD, FACS',
165 => 'Richard J. Lung MD',
166 => 'Andrew T. Lyos MD',
168 => 'Terry Maffi MD',
172 => 'Eric Mariotti MD',
173 => 'George Marosan FACS, MD',
174 => 'Kenneth Marshall MD',
177 => 'Alan Matarasso MD',
179 => 'Leo R. Mccafferty MD, FACS',
180 => 'Michael F. Mcguire MD',
181 => 'Peter Mckinney MD',
182 => 'Joseph Mele MD, FACS',
184 => 'Constantino Mendieta MD, FACS',
185 => 'Leonard Miller MD, FACS',
186 => 'Daniel C. Mills MD',
187 => 'Clayton L. Moliver MD',
188 => 'Daniel Morello MD',
192 => 'Foad Nahai FACS, MD',
193 => 'Nina Naidu MD, FACS',
194 => 'James D. Namnoum MD',
195 => 'Thomas Narsete MD',
197 => 'Alexander G. Nein MD, FACS',
199 => 'German Newall MD',
200 => 'Larry Nichter FACS, MD',
201 => 'Nicholas Nikolov MD',
202 => 'T. Gerald O\'Daniel MD',
203 => 'Stanley Okoro FACS, MD',
204 => 'Roger J. Oldham MD',
205 => 'Andrew P. Ordon MD, PhD',
206 => 'Douglas Ousterhout MD, DDS',
207 => 'Cemile Nurdan Ozturk MD',
208 => 'Humberto Palladino MD',
209 => 'Gregory Park MD',
210 => 'Paul Parker MD',
212 => 'Christopher Patronella MD',
213 => 'Malcolm Paul MD',
215 => 'Christine Petti MD, FACS',
216 => 'Tracy Pfeifer MD',
217 => 'Larry Pollack MD',
218 => 'Todd Pollock MD',
220 => 'Jason Pozner MD',
221 => 'Barry Press FACS, MD',
222 => 'Lee PU PhD, MD',
223 => 'Daniel Pyo MD',
224 => 'Talmage Raine MD',
228 => 'Norman Rappaport MD',
229 => 'David Reath MD',
230 => 'Dustin Reid MD',
232 => 'Neal R. Reisman MD, JD',
233 => 'Remus Repta MD',
234 => 'Richard Dale Reynolds MD',
235 => 'Steven Ringler MD, FACS',
236 => 'Michael Byun, MD',
237 => 'Rod Rohrich FACS, MD',
238 => 'Stephen J. Ronan MD',
239 => 'Ralph Rosato MD, FACS',
241 => 'Lorne Rosenfield FACS, MD',
242 => 'Andrew Rosenthal MD',
244 => 'J. Peter Rubin MD, FACS',
245 => 'Adam J. Rubinstein MD',
246 => 'Richard Sadove MD, FACS',
247 => 'Ali Sajjadian FACS, MD',
248 => 'Renato Saltz MD, FACS',
249 => 'Kenneth Salyer MD',
251 => 'Homayoun Sasson FACS, MD',
252 => 'Kamal Sawan FACS, MD',
253 => 'Adam D. Schaffner MD, FACS',
254 => 'Clark Schierle MD, PhD',
255 => 'Roy Semlacher MD, FRCSC',
256 => 'Manish H. Shah MD',
257 => 'Arthur Ship MD',
258 => 'Robert Silich FACS, MD',
259 => 'Robert Singer MD, FACS',
261 => 'David Smith MD',
262 => 'Raluan Soltero MD',
263 => 'Evan Sorokin FACS, MD',
264 => 'Sadri O. SOZER MD',
265 => 'Henry Spinelli MD',
267 => 'W. Grant Stevens MD',
268 => 'Paul Striker MD',
269 => 'James Stuzin MD',
270 => 'Sam Sukkar MD, FACS',
271 => 'Gregory Swank MD',
272 => 'Bahman Teimourian FACS, MD',
273 => 'Steven Teitelbaum MD',
275 => 'George Toledo MD',
276 => 'Bryant Toth MD',
278 => 'Terry Tubb MD',
279 => 'Andrew Turk FACS, MD',
280 => 'Lawrence Koplin MD',
281 => 'Fredrick Valauri MD',
284 => 'Jennifer Walden FACS, MD',
285 => 'Simeon Wall JR. MD, FACS',
286 => 'Stewart Wang FACS, MD',
287 => 'Victoria Veytsman',
288 => 'Larry Weinstein MD',
289 => 'J. Jason Wendel MD',
290 => 'Linton Whitaker MD',
291 => 'Thomas Wiener MD, FACS',
292 => 'Wesley G. Wilson MD',
293 => 'Garrett A. Wirth FACS, MD',
294 => 'Terry Dubrow MD',
295 => 'Michael Yaremchuk MD'
);

    foreach($data as $key=>$val)
    {
        //echo($key." => " . $val . "<br>");    
        $sql = "UPDATE doctors SET title='{$val}' WHERE id={$key}";
        mysql_query($sql, $conn); 
    }
    echo("end");
    
}

mysql_close($conn);
?>